spring.application.name=scandine
server.port=${PORT:8080}
//server.address=0.0.0.0

spring.datasource.url=${MYSQL_URL}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
